### ISSUE TITLE
Feature request: Diaspora* <-> Wordpress comment synchronization

### ISSUE THREAD

**Issue by earthbound19** [DiasPHPora/wp-to-diaspora#148]
This would be super duper awesome, and I know it's a hefty feature request.

For reference, this plugin (which it seems to me no longer works) has the feature: [https://wordpress.org/plugins/diasposter/](https://wordpress.org/plugins/diasposter/)

**Comment by noplanman** [comment]
Hi @earthbound19, thanks for your message.

Without having looked into this deeply, a few "classical" issues come to my head which could be a bit challenging.

**Privacy**: Maybe the people commenting on your blog don't want their name and comment to be shared anywhere else. And vice versa, people on diaspora\* might not like their texts to be published on your blog. Of course this isn't a problem if they explicitly agree to it, but then there's the question of how to solve *that*.

**Federation**: Due to the way diaspora\* federates content, it is very possible for there to be some sort of de-synchronisation, making the comments on diaspora\* be displayed in an incorrect order. This should be easily solvable on the WordPress side, as we have control over the data.

**Posting account***: Obviously there will be the question of which account is the poster of he comments, on both sides.

I'll look into the way diasposter attempts to solve this 👍 

@gutobenn Any ideas / input on this?

**Comment by earthbound19** [comment]
Hrm. For the posting account (third) problem, do you mean it raises a question of making it clear whether a comment originated at Wordpress or Diaspora? Jeepers. The only solution I can imagine right away is having that information appended to the comment itself e.g. "--via Wordpress" or "--via Diaspora*," which could be ugly and for many users confusing--what do they know or care about Wordpress or Diaspora if they're reading at one or the other and don't know about the other? If there's any way that text in the commenter attribution can be modified--and that would have to be changeable both at Wordpress and Diaspora* --that would be a better (and probably less visually intrusive) place to put information like that.

The first two, now I think on them, are deal killers, with a possible contextual solution for the first. For the first the context of synchronized comments could be restricted to only public posts at Diaspora*. I'm not sure whether it's feasible to know that under Diaspora's aspect model. Maybe that could be expressed through a post tag required for syncing e.g. #publicPost.

But federation delays causing out-of-order comments, I can't imagine a solution for that unless Diaspora itself has a protocol for dynamically sorting comments based on some established comment age.

**Comment by noplanman** [comment]
> a question of making it clear whether a comment originated at WordPress or Diaspora?

Also, but not what I meant. Only a diaspora (or any other federation software) account can post on diaspora. So you would either have to create a separate user that takes over the role of posting the WordPress comments to your diaspora post, or the comments get posted under the account that posts the post itself. Same thing applies to WordPress! Who is the author of the diaspora comments on your WordPress posts? Either a new dedicated user, or the post author.

What do you mean by "commenter attribution"? Taking the example above, using a custom account for the cross-commenting, this could be in the username itself.
i.e.:
- on diaspora: `"<username of commenter> - via WordPress"`
- on WordPress: `"<username of commenter> - via diaspora"`

I agree that the privacy problem can be circumvented by only cross-posting to and from public posts. This is totally doable, as WordPress knows if the post is public or not, no need for a hashtag I think.

What just came to my mind now though, what if somebody posts a post to diaspora multiple times with different settings? In that case, only the "latest" one would be the active one.


The comment sync is the most difficult part I feel. Synchronisation would happen in intervals, so even if the comment hasn't been federated from other pods yet, eventually it should be there. Important here is the time, which would need to be the same on WordPress and diaspora pod. On the WordPress side comments would be created using the time they were created on diaspora, so sorting isn't an issue, even if the comments from diaspora trickle in later. But obviously, if the time settings are different, it will be super difficult to follow a conversation.


In an ideal world I'd love to implement this feature, but I honestly think it's a huge effort to try and solve something that can't be fully controlled. So it's kind of like chasing tails :confused:

I'm not just burying this feature request, don't get me wrong! But if it should become a feature, it would be nice to have something working as a feature :+1:

**Comment by earthbound19** [comment]
Sorry I missed your reply--and yeah, that's why I said it would be hefty.

**Comment by bekopharm** [comment]
As for privacy: public is public. The blog is just another actor in the *verse. Same with Mastodon. Links to the source can be kept in the comment for reference.

I agree that privatly posted messages should not be touched tho.

The Indieweb offers various backfeed solutions for such systems. brid.gy comes to mind. It's foss and plugins can be added.

The trick is to catch Update and Delete. Mayhap this can be addressed with the API that Diaspora has now in dev since it offers access to the Timeline.

**Comment by noplanman** [comment]
I'll let any future dev who wants to pick this up re-open it.
